"""Add department field to User model

Revision ID: 5f0ca0b57ff9
Revises: e1cb46fb01a9
Create Date: 2025-05-08 16:18:30.852973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0ca0b57ff9'
down_revision = 'e1cb46fb01a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('department', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'department')
    # ### end Alembic commands ###
