"""Initial migration

Revision ID: e1cb46fb01a9
Revises: 
Create Date: 2025-01-15 14:47:49.262834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1cb46fb01a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(length=10), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('answers', sa.String(length=500), nullable=False),
    sa.Column('correct_answer', sa.String(length=5), nullable=False),
    sa.Column('passing_score', sa.Integer(), nullable=False),
    sa.Column('failing_score', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.String(length=10), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question_bank.question_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_responses')
    op.drop_table('user')
    op.drop_table('question_bank')
    # ### end Alembic commands ###
